name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # minimum supported version
      - uses: psf/black@stable
      - name: Install and run ruff
        run: |
          pip install ruff
          ruff check
      - name: Install and run vermin
        run: |
          pip install vermin
          # Run vermin and fail if any Python <3.10 features are detected
          vermin --eval-annotations -vvv --feature union-types deepinv examples | grep "3.10" && exit 1 || true